CRM_v2/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CRM_v2.Models
{
    public class Picture
    {
        public Picture(string path, string description)
        {
            Path = path;
            Description = description;
        }
        public string Path { get; set; }
        public string Description { get; set; }
    }
}

CRM_v2/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using CRM_v2.Models;

namespace CRM_v2.Controllers
{
      [Authorize(Roles = "Administrator,Client,Staff")]
    public class PictureController : ContrlLoggerController
    {
        // GET: /Picture
        public ActionResult Index()
        {
            return View(new PictureModel());
        }

        // GET: /Picture/Upload
        public ActionResult Upload()
        {
            return View();
        }

          //POST: /Picture/Upload
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(FormCollection form)
        {
            HttpPostedFileBase hpf = Request.Files["hpf"] as HttpPostedFileBase;

                string fileName = System.IO.Path.GetFileName(hpf.FileName);

                Picture image = new Picture(fileName, Request["description"]);
                PictureModel PictModel = new PictureModel();
                PictModel.Add(image, hpf);
            
            return RedirectToAction("Index");
        }

    }
}

CRM_v2/Views/Picture/Index.cshtml
@model CRM_v2.Models.PictureModel
@{
    ViewBag.Title = "Gallery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gallery</h2>

<table class="table" >
    @{foreach (var image in Model)
    {
        <tr >
            <td class="col-md-2">
                <img style="border:thick; border-radius:5px; border-color:darkgray;"  width="150" src="~/Images/@image.Path" />
            </td>
            <td class="col-md-2">
                <span class="description">@image.Description</span>
            </td>
            <td class="col-md-8">
            </td>
        </tr>
    }}
</table>
<div class="form-horizontal">
    <div>
        <p style="font-weight: bold; color:red">@{ @ViewBag.Comment  } </p>
    </div>
    @Html.ActionLink("Add picture", "Upload")
</div>

CRM_v2/Views/Picture/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upload</h2>


@using (Html.BeginForm("UpLoad", "Picture", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div>
        The default upload file limit is 4096 KB which is approximately 4MB<br />       
    </div>


    <fieldset>
        <h4>Add picture</h4>
        <p>
            <div class="editor-field" style="margin-bottom:auto;">
                <input type="file" name="hpf" />
            </div>
        </p>
        <p>
        <h4 >Add description</h4>
            <div style="margin:auto">
                <input type="text" name="description" />
            </div>
        </p>
    </fieldset>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" name="Submit" id="SubmitSingle" value="SavePicture" class="btn btn-default" />
                </div>
            </div>

            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>