CRM_v2/Controllers/AdminkaController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace CRM_v2.Controllers
{
     [Authorize(Roles = "Administrator")]
    public class AdminkaController : ContrlLoggerController
    {
        // GET: Adminka
       
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chat()
        {
            //return View("Chat");
            return RedirectToAction("Index", "Chat");
        }
    }
}

CRM_v2/Controllers/CtrlActStatisticaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using CRM_v2.Models;
using CRM_v2.DAL;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;

namespace CRM_v2.Controllers
{

    public class CtrlActStatisticaController : ContrlLoggerController
    {

        private UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult Find(string term)
        {

            var statistica = unitOfWork.CtrlActStatRepository.Get(usr => usr.UserName.StartsWith(term));
            var projection =  from usrst in statistica
                             select new
                             {
                                 label = usrst.UserName,
                                 value = usrst.UserName,
                             };

            var distinctWords = projection.Distinct();
            return Json(distinctWords.ToList(),
              JsonRequestBehavior.AllowGet);

        }


      // GET: /Statistica/

      //  public ViewResult Index(int? page)
      //{
      //   int pageSize = 10;
      //   int pageNumber = (page ?? 1);

      //    IEnumerable<CtrlActStat> statistica;

      //    //statistica = unitOfWork.UsrStatRepository.Get();
      //    statistica = unitOfWork.CtrlActStatRepository.Get(orderBy: q => q.OrderByDescending(d => d.StartExecution));
  
      //      return View(statistica.ToPagedList(pageNumber, pageSize));     
            
      //}

        public ViewResult Index(string currentFilter, string searchString, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            IEnumerable<CtrlActStat> statistica;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                statistica = unitOfWork.CtrlActStatRepository.Get(usr => usr.UserName.StartsWith(searchString), orderBy: usr => usr.OrderByDescending(d => d.StartExecution));
            }
            else
            {
               
                statistica = unitOfWork.CtrlActStatRepository.Get(orderBy: usr => usr.OrderByDescending(d => d.StartExecution));
            }
            return View(statistica.ToPagedList(pageNumber, pageSize));
        }



      // GET: /Statistica/Details/5
        
      public ViewResult Details(int id)
      {
         CtrlActStat statistica = unitOfWork.CtrlActStatRepository.GetByID(id);
         return View(statistica);
      }


       // GET: /Statistica/Edit/5
        
      public ActionResult Edit(int id)
      {
         CtrlActStat statistica = unitOfWork.CtrlActStatRepository.GetByID(id);
          return View(statistica);
      }
       // POST: /Statistica/Edit/5
        
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit(
           //[Bind(Include = "Id,UserName,LastLogin,LastAction")]
         CtrlActStat statistica)
      {
         try
         {
            if (ModelState.IsValid)
            {
               unitOfWork.CtrlActStatRepository.Update(statistica);
               unitOfWork.Save();
               return RedirectToAction("Index");
            }
         }
         catch (DataException /* dex */)
         {
            //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
         }
                        
         return View(statistica);
      }

      // GET: /Statistica/Delete/5
    
      public ActionResult Delete(int id)
      {
         CtrlActStat statistica = unitOfWork.CtrlActStatRepository.GetByID(id);
         return View(statistica);
      }

      //
      // POST: /Statistica/Delete/5
        
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         CtrlActStat course = unitOfWork.CtrlActStatRepository.GetByID(id);
         unitOfWork.CtrlActStatRepository.Delete(id);
         unitOfWork.Save();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         unitOfWork.Dispose();
         base.Dispose(disposing);
      }




   }
}

CRM_v2/Views/CtrlActStatistica/Details.cshtml
@model CRM_v2.Models.CtrlActStat

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CtrlActStat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Action)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Controller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Controller)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionParams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionParams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserHost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserHost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserAgent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserAgent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HttpMtthod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HttpMtthod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Form)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Form)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Query)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Query)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Referer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Referer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hearders)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hearders)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cookies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cookies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartExecution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartExecution)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishExecution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishExecution)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Back to List", "Index")
</p>

CRM_v2/Views/CtrlActStatistica/Index.cshtml
@using CRM_v2.Helpers;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@model IEnumerable<CRM_v2.Models.UsrStat>*@
@model PagedList.IPagedList<CRM_v2.Models.CtrlActStat>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Statistics";
}

<h2>Event statistics</h2>

<p>
   
    @Html.ActionLink("Back to Administration", "Index", "Adminka")

</p>
<link href="@Url.Content(
    "~/Content/CRM_scss/Style_autocomplete.css")"
      rel="Stylesheet" type="text/css" />
@using (Html.BeginForm("Index", "CtrlActStatistica", FormMethod.Get))
{
    <script type="text/javascript">
        $(function () {
            $("input#Search").val = '@ViewBag.CurrentFilter';
            var autocompleteUrl = '@Url.Action("Find")';
            $("input#Search").autocomplete({
                source: autocompleteUrl,
                minLength: 2,
                select: function (event, ui) {
                    //alert("Selected " + ui.item.UserName + " " + ui.item.LastAction);
                }
            });
        });
    </script>
    <h2>Search</h2>
    @*<p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>*@
    <div class="row">
        <div class="col-md-6">

            <label for="Search" class="col-md-3">User  </label>

            <input name="SearchString" type="text" id="Search" class="col-md-3" />
            <span style="padding-left:15px; padding-top:0px;">
                <input type="submit" value="Search" class="btn btn-primary" />
            </span>

        </div>
    </div>
}
@Html.Partial("Search")

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }))

</div>

CRM_v2/Views/CtrlActStatistica/Index_bad.cshtml
@model IEnumerable<CRM_v2.Models.CtrlActStat>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Action)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Controller)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActionParams)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OriginalUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserHost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserAgent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HttpMtthod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Form)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Query)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Referer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hearders)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cookies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartExecution)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinishExecution)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Action)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Controller)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActionParams)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OriginalUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserHost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserAgent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HttpMtthod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Form)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Query)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Referer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hearders)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cookies)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartExecution)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinishExecution)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CRM_v2/Views/CtrlActStatistica/Search.cshtml
                                    @*@model IEnumerable<CRM_v2.Models.CtrlActStat>*@
@model PagedList.IPagedList<CRM_v2.Models.CtrlActStat>
@using PagedList.Mvc;

<div class="row">
    <table id="CtrlActStatTbl" class=" table table-striped table-condensed table-bordered"style="margin-top:10px;">
        <thead>
            <tr class="row">
                <th class="col-md-1"></th>
                <th class="col-md-1">Action</th>
                <th class="col-md-1">Controller</th>
             
                <th class="col-md-1">UserHost</th>
               
                <th class="col-md-1">HttpMethod</th>
             
                <th class="col-md-1">UserName</th>
                <th class="col-md-3">StartExecution</th>
                <th class="col-md-3">FinishExecution</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr class="row">
                    <td class="col-md-1">
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </td>
                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.Action)
                    </td>

                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.Controller)
                    </td>

                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.UserHost)
                    </td>

                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.HttpMtthod)
                    </td>

                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td class="col-md-3">
                        @Html.DisplayFor(modelItem => item.StartExecution)
                    </td>
                    <td class="col-md-3">
                        @Html.DisplayFor(modelItem => item.FinishExecution)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>