CRM_v2/Controllers/AdminkaController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace CRM_v2.Controllers
{
     [Authorize(Roles = "Administrator")]
    public class AdminkaController : ContrlLoggerController
    {
        // GET: Adminka
       
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chat()
        {
            //return View("Chat");
            return RedirectToAction("Index", "Chat");
        }
    }
}

CRM_v2/Controllers/StatisticaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using CRM_v2.Models;
using CRM_v2.DAL;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;

namespace CRM_v2.Controllers
{

    public class StatisticaController : ContrlLoggerController
    {

        private UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult Find(string term)
        {

            var statistica = unitOfWork.UsrStatRepository.Get(usr => usr.UserName.StartsWith(term));
            var projection =  from usrst in statistica
                             select new
                             {
                                 label = usrst.UserName,
                                 value = usrst.UserName,
                             };

            var distinctWords = projection.Distinct();
            return Json(distinctWords.ToList(),
              JsonRequestBehavior.AllowGet);

        }


      // GET: /Statistica/

        public ViewResult Index( string currentFilter, string searchString, int? page)
      {
         int pageSize = 10;
         int pageNumber = (page ?? 1);
         IEnumerable<UsrStat> statistica;
               if (searchString != null)
                   {
                      page = 1;
                   }
                   else
                   {
                      searchString = currentFilter;
                   }

                   ViewBag.CurrentFilter = searchString;
                           if (!String.IsNullOrEmpty(searchString))
                           {
                                statistica = unitOfWork.UsrStatRepository.Get(usr => usr.UserName.StartsWith(searchString), orderBy: usr => usr.OrderByDescending(d => d.ModTime));
                           }
                           else
                           {
                                statistica = unitOfWork.UsrStatRepository.Get( orderBy: usr => usr.OrderByDescending(d => d.ModTime));
                           }
             return View(statistica.ToPagedList(pageNumber, pageSize));   
      }



      // GET: /Statistica/Details/5
        
      public ViewResult Details(int id)
      {
         UsrStat statistica = unitOfWork.UsrStatRepository.GetByID(id);
         return View(statistica);
      }


       // GET: /Statistica/Edit/5
        
      public ActionResult Edit(int id)
      {
         UsrStat statistica = unitOfWork.UsrStatRepository.GetByID(id);
          return View(statistica);
      }
       // POST: /Statistica/Edit/5
        
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit(
           [Bind(Include = "Id,UserName,LastLogin,LastAction")]
         UsrStat statistica)
      {
         try
         {
            if (ModelState.IsValid)
            {
               unitOfWork.UsrStatRepository.Update(statistica);
               unitOfWork.Save();
               return RedirectToAction("Index");
            }
         }
         catch (DataException /* dex */)
         {
            //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
         }
                        
         return View(statistica);
      }

      // GET: /Statistica/Delete/5
    
      public ActionResult Delete(int id)
      {
         UsrStat statistica = unitOfWork.UsrStatRepository.GetByID(id);
         return View(statistica);
      }

      //
      // POST: /Statistica/Delete/5
        
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         UsrStat course = unitOfWork.UsrStatRepository.GetByID(id);
         unitOfWork.UsrStatRepository.Delete(id);
         unitOfWork.Save();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         unitOfWork.Dispose();
         base.Dispose(disposing);
      }


      // GET: /Statistica/Create
        
      public ActionResult Create()

      {
          return View();
      }

        // POST: /Statistica/Create
         
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create(
          [Bind(Include = "Id,UserName,LastLogin,LastRole,LastAction, ModTime,isActive, isEnabled, LastActionTime")]
         UsrStat statistica)
      {
          try
          {
              if (ModelState.IsValid)
              {
                  string tmpId = User.Identity.GetUserId();
                  UsrStat write_st = new UsrStat(tmpId, "statistica.LastAction");
                  unitOfWork.UsrStatRepository.Insert(write_st);
                  unitOfWork.Save();
                  return RedirectToAction("Index");
              }
          }
          catch (DataException /* dex */)
          {
              //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
              ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
          }
     
          return View(statistica);
      }


         //// POST: /Statistica/CreateByUsr
         //[HttpPost]
         
         public void CreateByUsr()
         {
             try
             {

                 if (ModelState.IsValid)
                 {
                     string tmpId = User.Identity.GetUserId();
                     UsrStat write_st = new UsrStat(tmpId,"Login");
                     unitOfWork.UsrStatRepository.Insert(write_st);
                     unitOfWork.Save();
                     return ;
                 }
             }
             catch (DataException /* dex */)
             {
                 //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                 ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
             }

             return ;
         }
   }
}

CRM_v2/Views/Statistica/Create.cshtml
@model CRM_v2.Models.UsrStat

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Створити</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Statistics</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.LastAction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastAction, new { htmlAttributes = new { @class = "form-control" } })
              
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CRM_v2/Views/Statistica/Delete.cshtml
@model CRM_v2.Models.UsrStat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure?</h3>
<div>
    <h4>UsrStat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastLogin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLogin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastRole)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastRole)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastAction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastAction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastActionTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastActionTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CRM_v2/Views/Statistica/Details.cshtml
@model CRM_v2.Models.UsrStat

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>UsrStat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastLogin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLogin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastRole)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastRole)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastAction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastAction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastActionTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastActionTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CRM_v2/Views/Statistica/Edit.cshtml
@model CRM_v2.Models.UsrStat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsrStat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastLogin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastLogin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastLogin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastRole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastRole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isEnabled)
                    @Html.ValidationMessageFor(model => model.isEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastAction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastAction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastAction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastActionTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastActionTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastActionTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CRM_v2/Views/Statistica/Index.cshtml
@using CRM_v2.Helpers;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model PagedList.IPagedList<CRM_v2.Models.UsrStat>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Statistics";
}

<h2  >Events statistics</h2>

<p>
    @Html.ActionLink("New", "Create") |
    @Html.ActionLink("Back to Administration", "Index", "Adminka")

</p>
<link href="@Url.Content(
    "~/Content/CRM_scss/Style_autocomplete.css")"
      rel="Stylesheet" type="text/css" />
@using (Html.BeginForm("Index", "Statistica", FormMethod.Get))
{
    <script type="text/javascript">
        $(function () {
            $("input#Search").val= '@ViewBag.CurrentFilter';
            var autocompleteUrl = '@Url.Action("Find")';
            $("input#Search").autocomplete({
                source: autocompleteUrl,
                minLength: 2,
                select: function (event, ui) {
                    //alert("Selected " + ui.item.UserName + " " + ui.item.LastAction);
                }
            });
        });
    </script>
    <h2>Search</h2>

    <div class="row" >
        <div class="col-md-6">
           
            <label for="Search" class="col-md-3">User   </label>

            <input name="SearchString" type="text" id="Search" class="col-md-3" />
            <span style="padding-left:15px; padding-top:0px;">
                <input type="submit" value="Search" class="btn btn-primary" />
            </span>
            
        </div>
    </div>
}
@Html.Partial("Search")

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page,  currentFilter = ViewBag.CurrentFilter }))


   
</div>

CRM_v2/Views/Statistica/Search.cshtml
@model PagedList.IPagedList<CRM_v2.Models.UsrStat>
@using PagedList.Mvc;

<table id="UsrStatTbl" class=" table table-striped table-condensed table-bordered" style="margin-top:10px;">
    <thead>
        <tr>
            <th class="col-md-offset-0 col-md-3"></th>
            <th class="col-md-1">Id </th>
            <th class="col-md-1">UserName </th>
            <th class="col-md-2">LastRole </th>
            <th class="col-md-2">LastLogin </th>
            <th class="col-md-4">LastAction </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class=" col-md-offset-0 col-md-3">

                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                </td>
                <td class="col-md-1">
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td class="col-md-1">
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.LastRole)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.LastLogin)
                </td>
                <td class="col-md-4">
                    @Html.DisplayFor(modelItem => item.LastAction)
                </td>
            </tr>
        }
    </tbody>
</table>